### ISSUE TITLE
Dolby audio not working on connecting to a Bluetooth device

### ISSUE THREAD

**Issue by payalhrishabh** [reiryuki/Moto-Dolby-G-Pro-Magisk-Module#2]
Whenever i connect to a bluetooth device, it sometimes ask for the seting up new device but sometimes it doesn't ask. Also after connecting a bluetooth device the settings are changed to loudspeakers

**Comment by reiryuki** [comment]
Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, it will be closed immediately
