### ISSUE TITLE
Breaking YONO SBI lite with this module

### ISSUE THREAD

**Issue by AnkitSavani111** [reiryuki/Moto-Dolby-G-Pro-Magisk-Module#4]
Even Hiding everything in magisk also safetynet passed. Also all other banking apps fine only YONO SBI lite detecting root with this module previously worked fine. May be latest one has issue. Tried removing and adding latest module.

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

**Comment by AnkitSavani111** [comment]
Ohk sending everything

**Comment by AnkitSavani111** [comment]
[Dolby Logs.zip](https://github.com/reiryuki/Moto-Dolby-G-Pro-Magisk-Module/files/9404366/Dolby.Logs.zip)

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X (magisk install log is not magisk log)
3) Full logcat X (not using the right logcat app, 1 MB size minimum)
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

**Comment by AnkitSavani111** [comment]
Stable 5.5 fine Using it.

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.
